# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  schedule:
    # runs every day at 7:00 AM UTC in Jan, Feb, Sep-Dec
    - cron:  '0 7 * 1,2,9-12 *'

name: update_adv_stats

jobs:
  pfr_advstats:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Run update script
        run: Rscript -e 'source("auto/update_adv_stats.R")'

      - name: Commit updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data/adv_stats
          git commit -m "Automated advanced stats scrape `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
