on:
  schedule:
    # runs on March 15 automatically and otherwise on-demand.
    - cron:  '0 12 15 3 *'
  workflow_dispatch:

name: Update Combine Data

jobs:
  update:
    name: Update Combine Data
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Update combine
        run: Rscript -e 'source("auto/combine.R")'

      - name: Commit and push updated data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated combine data update `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
